[package]
name = "chip8rust"
version = "0.1.0"
authors = ["btwotwo"]
edition = "2018"

[dependencies]
rand = "0.7.0"
tui = {version ="0.6.2", features = ["crossterm"]}
crossterm = "^0.10"
lazy_static = "1.4.0"
bit-vec = "0.6"
